apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: ca-ops-referentiel-build
spec:
  serviceAccountName: caops-build
  source:
    git:
      url: https://github.com/xebia-france/coding-archi-ops.git
      revision: master
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.1.0
    args:
    - --context=/workspace/ca-ops-referentiel
    - --dockerfile=/workspace/ca-ops-referentiel/Dockerfile
    - --destination=gcr.io/coding-archi-ops/ca-ops-referentiel
    volumeMounts:
      - name: google-cloud-key
        mountPath: /secret
        readOnly: true
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/sa_credentials.json
  volumes:
  - name: google-cloud-key
    secret:
      secretName: appspot-cred
      items:
      - key: sa_json
        path: sa_credentials.json
