steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'ca-ops-referentiel/build.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dev-caops-cluster'